### ISSUE TITLE
IAR project is out of date

### ISSUE THREAD

**Issue by GorgonMeducer** [lvgl/lv_port_stm32f746_disco#18]
I followed the instruction and clone (incursively) the repository. 
In IAR, I got the following error:

![image](https://user-images.githubusercontent.com/13148491/148802108-96be6782-466a-40ef-81bd-90a2163dcf20.png)

It appears that the path is not right for files under asserts:

![image](https://user-images.githubusercontent.com/13148491/148802234-6d667c50-69e2-47ba-9077-59c50d39ac50.png)

![image](https://user-images.githubusercontent.com/13148491/148802280-8f9bb933-2198-4c46-b252-6ae6657432e6.png)

I am using the latest IAR (9.10.2)

Can you please fix this issue? Thanks.

**Comment by embeddedt** [comment]
I can't fix it, unfortunately, as I don't have IAR installed (and I use Linux, so I have no way of getting it easily).

I'll CC @canhkha as they originally contributed the project files.

**Comment by GorgonMeducer** [comment]
After further checking, it appears that this IAR project is completely out of date and hasn't been updated for quite a long time.

**Comment by embeddedt** [comment]
It might be more prudent to remove it for now, and it can be re-added if someone has interest in maintaining it. @kisvegabor What do you think?

**Comment by kisvegabor** [comment]
Good question. Constantly removing unmaintained parts is also a burden. Besides, if we remove them people wont't see them and it's less likely that someone sends an update once. 

I general, in case of something becomes out dated, I think the best would be to mention that in the README and open a `good-first-issue` issue about it.  What do you think? We can even have an issue in the lvgl repo where we reference these issues.

**Comment by embeddedt** [comment]
I'm concerned that leaving an unmaintained component in-tree might give the false impression that it still works (when it doesn't), but I don't have a better suggestion, so let's do it this way.

**Comment by kisvegabor** [comment]
Okay, I update the README (cc9296c) and opened an issue (#19)

**Comment by embeddedt** [comment]
Thanks! In that case, I suppose we can close this.

**Comment by abdalrahman01** [comment]
I had the same issue, I fixed it by updating the configurations: 
Project -> Edit Configurations  -> new (make a new one based on a previus ones)
