### ISSUE TITLE
Update the IAR project

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_stm32f746_disco#19]
The IAR project is out dated and needs to be updated to the latest LVGL version.

**Comment by GorgonMeducer** [comment]
After creating the cmsis-pack, I think I finally gain sufficient knowledge to fix this IAR project.
I will do it, maybe tomorrow.

**Comment by GorgonMeducer** [comment]
Done as promised. https://github.com/lvgl/lv_port_stm32f746_disco/pull/20
