### ISSUE TITLE
undefined reference to 'lv_demo-music'...

### ISSUE THREAD

**Issue by epikao** [lvgl/lv_port_stm32f746_disco#23]
Hello,

with CubeIDE, and if I change to lv_demo_music instead of _demo_widget and activate it in lv_conf.h I receive following error:

![image](https://user-images.githubusercontent.com/26655950/155693618-46aa387b-a54b-46ba-89bb-5c93f2aa959b.png)

What am i doing wrong?

Thank you

**Comment by kisvegabor** [comment]
Please confirm these:
- The `lv_demos` repo and `lv_demo_conf.h` is not part of the project (can be leftovers)
- `lvgl/demos/lv_demo_music` is really there
- Adding `#error "test"` to `lv_demo_music.c` show the error when you build the project
