### ISSUE TITLE
How to port it for stm32f7508-dk.

### ISSUE THREAD

**Issue by anand-010** [lvgl/lv_port_stm32f746_disco#25]
stm32f7508-dk is verry similar to stm32f746_disco i've tried to run it with liker file and few modification but it always shows black screen.
How do i port it for stm32f7508-dk?.

**Comment by embeddedt** [comment]
Hello! We use GitHub issues for development-related discussions.
Please use the [forum](https://forum.lvgl.io/) to ask questions.
